subroutine foo2()
 use pfunit
 call throw(Exception('foo2 was called'))
end subroutine foo2
