subroutine foo_3()
 use pfunit
 call throw(Exception('foo3 was called'))
end subroutine foo_3
